version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:80"
    environment:
      JWT_SECRET: changeme
      BANK_HOST: bank           # DNS interno → servicio bank
      BANK_PORT: 22
      BANK_USER: pivot_user
      BANK_KEY: /keys/pivot_user   # PEM privado, no .ppk
    volumes:
      - ./keys:/keys             # contiene pivot_user (priv) y pivot_user.pub
    depends_on:
      - bank

  bank:
    image: atmoz/sftp
    command: "pivot_user:::1001"   # crea usuario UID=1001, home=/home/pivot_user
    volumes:
      - ./bank-data:/home/pivot_user/upload         # dir donde subiremos archivos
      - ./keys/pivot_user.pub:/home/pivot_user/.ssh/authorized_keys:ro
